version: "3.3"

services:
  product:
    image: 'mysql:latest'
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'product_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
  order:
    image: 'mysql:latest'
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'order_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
